server:
  port: 9090                   # Порт сервиса А (например, 8080)

management.endpoints.web.exposure.include: info, health

#spring:
#  application:
#    name: service-b            # Логическое имя сервиса A
#  cloud:
#    consul:
#      host: localhost          # Адрес Consul (по умолчанию localhost)
#      port: 8500               # Порт Consul (8500 по умолчанию)
#      discovery:
#        service-name: service-b  # Необязательно, по умолчанию берётся spring.application.name
#        health-check-path: /actuator/health
#      config:
#        enabled: true            # Включаем Consul Config для внешней конфигурации
#        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
#        defaultContext: application  # Контекст по умолчанию

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.zalando.logbook: DEBUG