server:
  port: 8080                   # Порт сервиса А (например, 8080)

management.endpoints.web.exposure.include: info, health


#spring:
#  application:
#    name: service-a
#  config:
#    import:
#      - consul
#  cloud:
#    consul:
#      host: localhost          # Адрес Consul (по умолчанию localhost)
#      port: 8500               # Порт Consul (8500 по умолчанию)
#      discovery:
#        health-check-path:
#        health-check-url: http://dockerhost:8080/actuator/health

#      config:
#        enabled: true            # Включаем Consul Config для внешней конфигурации
#        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
#        defaultContext: application  # Контекст по умолчанию

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.zalando.logbook: DEBUG